name: Coverage
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "coverage"
      - name: Create test fixture directories
        run: |
          mkdir -p org-core/tests/fixtures
          # Create minimal test fixtures if they don't exist
          if [ ! -f org-core/tests/fixtures/with_ids.org ]; then
            echo "* Heading with Simple ID" > org-core/tests/fixtures/with_ids.org
            echo ":PROPERTIES:" >> org-core/tests/fixtures/with_ids.org
            echo ":ID: simple-123" >> org-core/tests/fixtures/with_ids.org
            echo ":END:" >> org-core/tests/fixtures/with_ids.org
          fi
      - name: Run tests with coverage
        run: |
          cargo build
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Generate coverage summary
        run: |
          cargo build
          cargo llvm-cov --all-features --workspace --summary-only > coverage-summary.txt
          echo "## Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat coverage-summary.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
          verbose: true
          flags: unittests
          name: codecov-umbrella
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            lcov.info
            coverage-summary.txt
          retention-days: 30
